include_directories(${TARGET_INCLUDE})
if(LIB_SHARE)
	add_library(${TARGET_NAME} SHARED ${TARGET_SRCS})
	#target_link_libraries(${TARGET} ${TARGET_USE_LIB})
endif(LIB_SHARE)
if(LIB_STATIC)
	add_library(${TARGET_NAME} STATIC ${TARGET_SRCS})
	#target_link_libraries(${TARGET} ${TARGET_USE_LIB})
endif(LIB_STATIC)
if(BINARY)
	add_executable(${TARGET_NAME} ${TARGET_SRCS})
	#target_link_libraries(${TARGET} ${TARGET_USE_LIB})
endif(BINARY)
